package com.project.org.hr;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "Details of the applicant")
public class applicant extends com.project.org.hr.person implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "Email of the Applicant")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String email;

    @org.kie.api.definition.type.Label(value = "Resume of the Applicant")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String resume;

    public applicant() {
    }
    
    public applicant(java.lang.String resume, java.lang.String email) {
        this.resume = resume;
        this.email = email;
    }

    public java.lang.String getEmail() {
        return this.email;
    }
    
    public void setEmail(java.lang.String email) {
        this.email = email;
    }

    public java.lang.String getResume() {
        return this.resume;
    }
    
    public void setResume(java.lang.String resume) {
        this.resume = resume;
    }

}