package com.project.org.hr;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "Details of the Employee")
public class employee extends com.project.org.hr.person implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "Id of the Employee")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer empid;

    public employee() {
    }
    
    public employee(java.lang.Integer empid) {
        this.empid = empid;
    }

    public java.lang.Integer getEmpid() {
        return this.empid;
    }
    
    public void setEmpid(java.lang.Integer empid) {
        this.empid = empid;
    }

}