package com.project.org.hr;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "HR Interviewer")
public class hrinter extends com.project.org.hr.employee implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public hrinter() {
    }

}