package com.project.org.hr;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("HR Interviewer")
public class hrinter extends com.project.org.hr.employee implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "Accepted by HR")
	@org.kie.api.definition.type.Position(value = 0)
	private java.lang.Boolean hraccepted;

	public java.lang.Boolean getHraccepted() {
		return this.hraccepted;
	}

	public void setHraccepted(java.lang.Boolean hraccepted) {
		this.hraccepted = hraccepted;
	}

	public hrinter() {
	}

	public hrinter(java.lang.Boolean hraccepted) {
		this.hraccepted = hraccepted;
	}

}