package com.project.org.hr;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "Details of a person")
public class person implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "Age of any person")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Integer age;

    @org.kie.api.definition.type.Label(value = "Name of any person")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String name;

    public person() {
    }
    
    public person(java.lang.String name, java.lang.Integer age) {
        this.name = name;
        this.age = age;
    }

    public java.lang.Integer getAge() {
        return this.age;
    }
    
    public void setAge(java.lang.Integer age) {
        this.age = age;
    }

    public java.lang.String getName() {
        return this.name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }

}