package com.project.org.hr;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Technical Interviewer")
public class techinter extends com.project.org.hr.employee implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "Accepted by Technical")
	@org.kie.api.definition.type.Position(value = 0)
	private java.lang.Boolean techaccepted;

	public java.lang.Boolean getTechaccepted() {
		return this.techaccepted;
	}

	public void setTechaccepted(java.lang.Boolean techaccepted) {
		this.techaccepted = techaccepted;
	}

	public techinter() {
	}

	public techinter(java.lang.Boolean techaccepted) {
		this.techaccepted = techaccepted;
	}

}